import React, {useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,Check,FileText,Plus,ShieldCheck,X,ChevronLeft,ChevronRight,Download,Copy,Info} from 'lucide-react';
import {categories} from './questions.js';
import {STORAGE_KEY,loadSession,sampleSession,newSession,allQuestions,stateOf,counts} from './model.js';
import {generateRequirements,toMarkdown,toPlainText,toDocx,fileName} from './brd.js';
import '../../shared/base.css';
import './style.css';

const hints=['Let’s start with the bigger picture. What should the new system make possible?','Let’s map the systems, data, and security requirements that need to work together.','Let’s understand the experience for your recruitment team and your candidates.','Let’s look at how your people learn, develop, and build new skills.','Let’s walk through payroll, approvals, and the impact on your finance team.','Let’s explore how you support performance, feedback, and future leaders.','Let’s turn the conversation into a practical checklist. Choose Yes, No, or Partial and add context.'];
function Modal({title,children,onClose,wide=false}){
  const ref=useRef();
  useEffect(()=>{const el=ref.current;el.showModal();return()=>el.close();},[]);
  return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={onClose} aria-labelledby="modal-title"><div className="modal-heading"><h2 id="modal-title">{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;
}
function App(){
  const [initial]=useState(()=>{try{return loadSession(window.localStorage);}catch{return {session:sampleSession(),warning:'Browser storage is unavailable. Export your document before leaving.'};}});
  const [session,setSession]=useState(initial.session),[category,setCategory]=useState(0),[modal,setModal]=useState(null),[warning,setWarning]=useState(initial.warning||''),[saving,setSaving]=useState('Saved in this browser'),[toast,setToast]=useState(''),[customText,setCustomText]=useState(''),[busy,setBusy]=useState(false);
  const all=allQuestions(session),total=counts(all,session.answers),current=categories[category],questions=all.filter(q=>q.categoryId===current.id),done=counts(questions,session.answers),percent=Math.round((total.answered+total.na)/total.total*100);
  useEffect(()=>{if(warning)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(session));setSaving('Saved in this browser');}catch{setSaving('Not saved — export before leaving');}},[session,warning]);
  useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(id);}},[toast]);
  function update(id,patch){setSession(s=>({...s,answers:{...s.answers,[id]:{...s.answers[id],...patch}}}));}
  function navigate(i){setCategory(i);window.scrollTo({top:0,behavior:'instant'});}
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);setToast('Document downloaded');}
  async function exportDocx(){setBusy(true);try{download(await toDocx(generateRequirements(session)),fileName(session,'docx'));}catch{setToast('Word export failed. Please try the text download.');}finally{setBusy(false);}}
  async function copy(format){try{const d=generateRequirements(session);await navigator.clipboard.writeText(format==='markdown'?toMarkdown(d):toPlainText(d));setToast(format==='markdown'?'Markdown copied':'Plain text copied');}catch{setToast('Clipboard unavailable. Use the text download instead.');}}
  const doc=modal==='brd'?generateRequirements(session):null;
  return <><a className="skip-link" href="#questionnaire">Skip to questions</a><header className="app-header"><a className="brand" href="./"><span className="icon-mark">d/</span>discovery assistant<span className="version mono">v1.0</span></a><a className="text-link" href="https://adil-khb.github.io/-portfolio/">-&gt; / portfolio <ArrowUpRight size={14}/></a></header>
    <div className="app-shell"><aside className="sidebar"><div className="sidebar-top"><span className="eyebrow">workspace / discovery</span><h2>{session.client}</h2><p>{session.project}</p>{session.sample&&<span className="sample-badge mono">sample scenario</span>}</div><div className="overall"><div><span className="eyebrow">session progress</span><strong>{percent}%</strong></div><progress max="100" value={percent} aria-label="Overall completion"/><p>{total.answered} answered · {total.pending} pending{total.na>0&&` · ${total.na} N/A`}</p></div><nav className="category-nav" aria-label="Discovery categories">{categories.map((c,i)=>{const n=counts(all.filter(q=>q.categoryId===c.id),session.answers);return <button key={c.id} aria-current={category===i?'step':undefined} className={category===i?'active':''} onClick={()=>navigate(i)}><span className="category-number">{String(i+1).padStart(2,'0')}</span><span>{c.short}<small>{n.answered}/{n.total} answered{n.na>0&&` · ${n.na} N/A`}</small></span>{n.pending===0?<Check className="category-check" size={15}/>:<span className="pending-dot"/>}</button>;})}</nav><div className="sidebar-bottom"><button className="text-button" onClick={()=>setModal('about')}><Info size={16}/> About this tool</button><p><ShieldCheck size={15}/> Your answers stay in this browser.</p><span className="eyebrow">built by adil khodabacchus</span></div></aside>
    <main id="questionnaire" className="workspace"><div className="workspace-top"><span className="eyebrow">discovery / <span className="teal">{current.short.toLowerCase()}</span></span><span className="save-state"><Check size={13}/>{saving}</span></div>{warning&&<div className="notice" role="alert"><p>{warning}</p><button onClick={()=>setWarning('')} className="secondary">Continue with sample</button></div>}<div className="intro-note"><span>Try this with the sample scenario, or start your own discovery session.</span><button className="text-link" onClick={()=>setModal('new')}>-&gt; / new session</button></div><div className="section-top"><div><span className="eyebrow teal">section {String(category+1).padStart(2,'0')} / 07</span><h1>{current.title}</h1><p>{hints[category]}</p></div><span className="section-counter mono">{done.answered+done.na}<span> / {done.total}</span></span></div>
    <div className="questions">{questions.map((q,i)=>{const a=session.answers[q.id]||{},status=stateOf(q,a);return <section className="question" key={q.id}><div className="question-label"><span className="q-number mono">{String(i+1).padStart(2,'0')}</span><label htmlFor={q.id}><h2>{q.text}</h2></label><span className={`answer-state ${status}`}>{status==='answered'?<Check size={12}/>:null}{status==='na'?'not applicable':status}</span></div>{q.checklist&&<fieldset className="choice-group" disabled={a.na}><legend className="sr-only">{q.text}</legend>{['Yes','No','Partial'].map(choice=><label key={choice} className={a.choice===choice?'selected':''}><input type="radio" name={`${q.id}-choice`} checked={a.choice===choice} onChange={()=>update(q.id,{choice})}/>{choice}</label>)}{a.choice&&<button className="clear-choice" onClick={()=>update(q.id,{choice:''})}>Clear selection</button>}</fieldset>}<textarea id={q.id} aria-label={q.checklist?`Notes: ${q.text}`:q.text} value={a.text||''} disabled={Boolean(a.na)} onChange={e=>update(q.id,{text:e.target.value})} placeholder={q.checklist?'Add context, expectations, or a follow-up…':'Capture the client’s answer in their own words…'} rows={q.checklist?3:4}/><div className="answer-meta"><span>{q.checklist?'Supporting notes':'Client response'}{q.custom?' · custom question':''}</span><label className="na-label"><input type="checkbox" checked={Boolean(a.na)} onChange={e=>update(q.id,{na:e.target.checked})}/>Not applicable</label></div></section>;})}</div>
    <button className="add-question" onClick={()=>{setCustomText('');setModal('custom');}}><Plus size={16}/> Add a question to this section</button><div className="section-navigation"><button className="text-button" disabled={category===0} onClick={()=>navigate(category-1)}><ChevronLeft size={16}/> Previous section</button>{category<6?<button className="secondary" onClick={()=>navigate(category+1)}>Next section <ChevronRight size={16}/></button>:<span className="eyebrow">you’ve reached the last section</span>}</div><div className="generate-bar"><div><h3>From conversation to requirements.</h3><p>Demo / template mode. An LLM API could polish raw answers into formal requirement language.</p></div><button className="primary" onClick={()=>setModal('brd')}><FileText size={17}/> Generate BRD <ArrowUpRight size={16}/></button></div></main></div>
    {modal==='new'&&<Modal title="Start a discovery session" onClose={()=>setModal(null)}><p className="dialog-intro">Give this conversation a home. Starting a session replaces the one saved in this browser—export any answers you want to keep first.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!String(f.get('client')).trim()||!String(f.get('project')).trim())return;setSession(newSession(String(f.get('client')),String(f.get('project'))));setWarning('');setCategory(0);setModal(null);window.scrollTo(0,0);}}><label className="form-label">Client name<input name="client" required maxLength={140} placeholder="e.g. Northstar Services" autoFocus/></label><label className="form-label">Project name<input name="project" required maxLength={180} placeholder="e.g. HR & payroll transformation"/></label><div className="dialog-actions"><button type="button" className="secondary" onClick={()=>{setSession(sampleSession());setWarning('');setCategory(0);setModal(null);}}>Use sample scenario</button><button className="primary" type="submit">Start session <ArrowRight size={16}/></button></div></form></Modal>}
    {modal==='custom'&&<Modal title="Add a discovery question" onClose={()=>setModal(null)}><p className="dialog-intro">This question will be added to {current.title}.</p><form onSubmit={e=>{e.preventDefault();if(!customText.trim())return;const q={id:crypto.randomUUID(),text:customText.trim(),checklist:category===6,custom:true};setSession(s=>({...s,custom:{...s.custom,[current.id]:[...(s.custom[current.id]||[]),q]}}));setModal(null);setToast('Question added');}}><label className="form-label">Question<textarea value={customText} onChange={e=>setCustomText(e.target.value)} autoFocus required maxLength={1000}/></label><div className="dialog-actions"><button className="secondary" type="button" onClick={()=>setModal(null)}>Cancel</button><button className="primary" type="submit">Add question <Plus size={16}/></button></div></form></Modal>}
    {modal==='about'&&<Modal title="About this tool" onClose={()=>setModal(null)}><div className="about-copy"><p>The discovery structure in this tool is adapted from a published HCM selection framework — covering strategic alignment, departmental requirements (IT, Recruitment, L&D, Finance & Payroll, Performance), and a requirements checklist — reworked here into an interactive, live-capture format.</p><p>The sample company and its answers are fictional. Documents are generated using templates, without an AI API. Answers stay in your browser’s local storage and are never sent to a server. Anyone using this browser profile can access the saved session.</p><p>Built by Adil Khodabacchus to explore a more practical flow from discovery conversations to documented requirements.</p></div></Modal>}
    {doc&&<Modal title="Your requirements document" onClose={()=>setModal(null)} wide><div className="export-actions"><button className="secondary" onClick={()=>copy('markdown')}><Copy size={15}/> Copy Markdown</button><button className="secondary" onClick={()=>copy('plain')}>Copy plain text</button><button className="secondary" onClick={()=>download(new Blob([toPlainText(doc)],{type:'text/plain;charset=utf-8'}),fileName(session,'txt'))}><Download size={15}/> .txt</button><button className="primary" disabled={busy} onClick={exportDocx}><Download size={15}/> {busy?'Preparing…':'Download .docx'}</button></div><article className="document"><span className="document-kicker">DISCOVERY DRAFT / {doc.sample?'FICTIONAL SAMPLE':'CLIENT REQUIREMENTS'}</span><h1>{doc.title}</h1><dl><dt>Client</dt><dd>{doc.client}</dd><dt>Project</dt><dd>{doc.project}</dd><dt>Session started</dt><dd>{doc.date}</dd></dl><p className="document-summary">{total.answered} answered · {total.pending} outstanding · {total.na} not applicable. Template-generated from captured answers; stakeholder review required.</p>{doc.sections.map(s=><section key={s.title}><h2>{s.title}</h2>{s.items.length?s.items.map((i,j)=><div key={j}><h3>{i.question}</h3><p>{i.answer}</p></div>):<p>No answers captured in this category.</p>}</section>)}<section><h2>Open Questions / Outstanding Items</h2>{doc.outstanding.length?<ul>{doc.outstanding.map((i,j)=><li key={j}><strong>{i.category}:</strong> {i.question}{i.notes&&<p>Notes captured (decision pending): {i.notes}</p>}</li>)}</ul>:<p>No outstanding items.</p>}</section>{doc.notApplicable.length>0&&<section><h2>Not Applicable</h2><ul>{doc.notApplicable.map((i,j)=><li key={j}>{i.category}: {i.question}{i.notes&&<p>{i.notes}</p>}</li>)}</ul></section>}</article></Modal>}{toast&&<div role="status" className="toast">{toast}</div>}
  </>;
}
createRoot(document.getElementById('root')).render(<App/>);
